public enum EPacketId
{
	NONE,
	CREATE_ROOM_REQ,
	CREATE_ROOM_RES,
	ROLL_DICE_REQUEST,
	JOIN_RANDOM_ROOM_REQ,
	PLAYER_JOIN_NOTI,
	START_GAME_NOTI,
	ROLL_DICE_RESPONSE,
	CHANGE_TURN_NOTI,
	MAX = CHANGE_TURN_NOTI + 1,
}
